### ISSUE TITLE
[1.2.2 강화 학습으로 반응형 문제 해결]

### ISSUE THREAD

**Issue by rosesua318** [ArchiveElder/MachineLearning#1]
p38에서 강화 학습의 일반적인 구조가 설명이 되어있고, 앞 문장에서 강화 학습에는 여러 하위 분류가 있다고 했는데 다른 구조들은 어떠한 것이 있는지 알려주실 분 🙌

**Comment by Vector1331** [comment]
민서야 참 좋은 질문이구나! 

일반적으로 
강화학습의 행위자(Agent) 는 환경에 따라 보상(Reward)을 최대화하는행동(Action)을 하는데,  
(이 부분이 책에서 설명하는 일반적인 구조) 

이때 주어진  상태(State)에서  행하는 행동을 연결짓는 함수를 **Policy**라 하고, 
상태와 행동에 따라 발생할 보상을 예측하는 함수를 **value funtion**이라 한다. 
그리고 환경 내의 다음 상태와 보상이 어떨지에 대해 행위자의 예측을 **Model** 인건데, 


이제 첫번째 구조는 강화학습의 구분을 환경에 대한 model이 존재하냐, 안하냐로 구분하는거래
**(Model free와 model-based로 구분 )** 
(Model을 사용하는 agent를 model-based라고 부르고 그렇지 않은 agent를 model-free) 

또 다른 강화학습의 구조는 value funtion과 policy의 사용 여부로 구분하는 거래

model이 있다면 변화 예상이 가능해서 최적 행동 계획이 가능하겠지만, 아무래도 model을 알아내기 어려움이 존재하고 불확실한 model은 행위자의 행동에 대한 오류로 이어져서 오히려 좋은 행위자를 만드는데 방해가 될 수 있대.

Value-based agent와 policy-based agent의 경우에도 다양하게 분류되는 것 같아서 이 부분은 궁금하면 더 찾아보면 될 듯! 

나는 https://dreamgonfly.github.io/blog/rl-taxonomy/ 를 참고했어~ ! 
좋은 하루 되길 ~ 🐸
