### ISSUE TITLE
2.1.2 퍼셉트론 학습 규칙

### ISSUE THREAD

**Issue by Vector1331** [ArchiveElder/MachineLearning#2]
퍼셉트론 학습규칙 부분 제대로 이해 안가는데 
아래 식을 설명해줄 사람! 
![image](https://user-images.githubusercontent.com/89854207/162618826-0b575bf1-fed9-4e54-84b2-730214553fcf.png)

**Comment by rosesua318** [comment]
분류를 하기 위해 결정 함수를 정의해야 하는데, 결정함수를 정의할 때 가중치를 정의해서 샘플과 벡터 점곱을 해야 합니다.
위에 보이는 값은 가중지 w에 대한 업데이트 값인데, 이걸 하는 이유는 처음에 가중치를 0 또는 랜덤한 작은 값으로 초기화 시켰기 때문에 각 훈련 샘플 x(i)에 맞는 가중치를 업데이트 시키기 위해 필요한 값이라고 이해했습니다.
즉, 가중지 w의 변화량은 i번째 훈련 샘플의 진짜 클래스 레이블에서 훈련 샘플을 예측한 클래스 레이블의 차이를 구하여 학습률에 곱한 뒤, 그 값을 i번째 훈련 샘플에 곱하여 구한다는 것을 식으로 표현한 것이죠.
따라서, 밑의 식은 가중치가 변화량과 더해져 값이 업데이트 된다는 것을 나타내는 것입니다.
제가 이해한 게 틀렸을 수도 있으니까 다른 분들도 의견 주시면 좋겠네요😊

**Comment by ahneve** [comment]
나도 민서랑 이해한게 비슷한데, 수식을 말로 풀어 써보면

j번째 가중치의 변화량 = 학습률 * (i번째 타깃 값 - i번째 예측값) * i번째 샘플값의 j번째 특성 
이라서 
i번째 타깃값과 i번째 예측값이 동일한 경우 => j번째 가중치의 변화량은 0이 될거고,
i번째 타깃값과 i번째 예측값이 동일하지 않은 경우 => j번째 가중치의 변화량은 n이 될 거기 때문에

두번째 수식에서 이 변화량을 더해 업데이트 해준다고 이해했어!

**Comment by eilyri** [comment]
가중치에 업데이트 할 값을 계산해서 j번째 가중치에 그 값을 더해 새로운 가중치를 계산하는 식으로 이해했어!

클래스 레이블을 정확히 예측한 경우 -> 가중치를 업데이트 할 필요 없음(업데이트할 값이 0임!)
잘못 예측한 경우 -> 퍼셉트론 학습 규칙에 따라 업데이트 할 값 계산해서 더해준다.
